// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/tonytcb/inventory-management-system/internal/domain"
)

// FXRateRepository is an autogenerated mock type for the FXRateRepository type
type FXRateRepository struct {
	mock.Mock
}

type FXRateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FXRateRepository) EXPECT() *FXRateRepository_Expecter {
	return &FXRateRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *FXRateRepository) Save(_a0 context.Context, _a1 *domain.FXRate) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FXRate) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FXRateRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type FXRateRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *domain.FXRate
func (_e *FXRateRepository_Expecter) Save(_a0 interface{}, _a1 interface{}) *FXRateRepository_Save_Call {
	return &FXRateRepository_Save_Call{Call: _e.mock.On("Save", _a0, _a1)}
}

func (_c *FXRateRepository_Save_Call) Run(run func(_a0 context.Context, _a1 *domain.FXRate)) *FXRateRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.FXRate))
	})
	return _c
}

func (_c *FXRateRepository_Save_Call) Return(_a0 error) *FXRateRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FXRateRepository_Save_Call) RunAndReturn(run func(context.Context, *domain.FXRate) error) *FXRateRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewFXRateRepository creates a new instance of FXRateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFXRateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FXRateRepository {
	mock := &FXRateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
