// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// QueryRower is an autogenerated mock type for the QueryRower type
type QueryRower struct {
	mock.Mock
}

type QueryRower_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryRower) EXPECT() *QueryRower_Expecter {
	return &QueryRower_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, sql, arguments
func (_m *QueryRower) Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, arguments...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, sql, arguments...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryRower_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type QueryRower_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...interface{}
func (_e *QueryRower_Expecter) Exec(ctx interface{}, sql interface{}, arguments ...interface{}) *QueryRower_Exec_Call {
	return &QueryRower_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, arguments...)...)}
}

func (_c *QueryRower_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...interface{})) *QueryRower_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryRower_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *QueryRower_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryRower_Exec_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)) *QueryRower_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *QueryRower) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// QueryRower_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type QueryRower_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *QueryRower_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *QueryRower_QueryRow_Call {
	return &QueryRower_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *QueryRower_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *QueryRower_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryRower_QueryRow_Call) Return(_a0 pgx.Row) *QueryRower_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryRower_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...interface{}) pgx.Row) *QueryRower_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueryRower creates a new instance of QueryRower. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryRower(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryRower {
	mock := &QueryRower{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
