// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// QueryRower is an autogenerated mock type for the QueryRower type
type QueryRower struct {
	mock.Mock
}

type QueryRower_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryRower) EXPECT() *QueryRower_Expecter {
	return &QueryRower_Expecter{mock: &_m.Mock}
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *QueryRower) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// QueryRower_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type QueryRower_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *QueryRower_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *QueryRower_QueryRow_Call {
	return &QueryRower_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *QueryRower_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *QueryRower_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryRower_QueryRow_Call) Return(_a0 pgx.Row) *QueryRower_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryRower_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...interface{}) pgx.Row) *QueryRower_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueryRower creates a new instance of QueryRower. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryRower(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryRower {
	mock := &QueryRower{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
