// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// UpdateRateHandler is an autogenerated mock type for the UpdateRateHandler type
type UpdateRateHandler struct {
	mock.Mock
}

type UpdateRateHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateRateHandler) EXPECT() *UpdateRateHandler_Expecter {
	return &UpdateRateHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: c
func (_m *UpdateRateHandler) Handle(c *gin.Context) {
	_m.Called(c)
}

// UpdateRateHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type UpdateRateHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - c *gin.Context
func (_e *UpdateRateHandler_Expecter) Handle(c interface{}) *UpdateRateHandler_Handle_Call {
	return &UpdateRateHandler_Handle_Call{Call: _e.mock.On("Handle", c)}
}

func (_c *UpdateRateHandler_Handle_Call) Run(run func(c *gin.Context)) *UpdateRateHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UpdateRateHandler_Handle_Call) Return() *UpdateRateHandler_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *UpdateRateHandler_Handle_Call) RunAndReturn(run func(*gin.Context)) *UpdateRateHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdateRateHandler creates a new instance of UpdateRateHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateRateHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateRateHandler {
	mock := &UpdateRateHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
